//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aphysoft.Share.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aphysoft.Share.Resources.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v2.1.3 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=a.document,m=&quot;2.1.3&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery {
            get {
                return ResourceManager.GetString("jquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! History.js jQuery Adapter (updated 6/1/2014) */
        ///(function (window, undefined) {
        ///    &quot;use strict&quot;;
        ///
        ///    // Localise Globals
        ///    var
        ///		History = window.History = window.History || {},
        ///		jQuery = window.jQuery;
        ///
        ///    // Check Existence
        ///    if (typeof History.Adapter !== &apos;undefined&apos;) {
        ///        throw new Error(&apos;History.js Adapter has already been loaded...&apos;);
        ///    }
        ///
        ///    // Add the Adapter
        ///    History.Adapter = {
        ///        /**
        ///		 * History.Adapter.bind(el,event,callback)
        ///		 * @param {Element|st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string libs {
            get {
                return ResourceManager.GetString("libs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! Modernizr v2.6.2 www.modernizr.com */
        ///window.Modernizr = (function (window, document, undefined) {
        ///
        ///    var version = &apos;2.6.2&apos;,
        ///
        ///    Modernizr = {},
        ///
        ///    /*&gt;&gt;cssclasses*/
        ///    // option for enabling the HTML classes to be added
        ///    enableClasses = true,
        ///    /*&gt;&gt;cssclasses*/
        ///
        ///    docElement = document.documentElement,
        ///
        ///    /**
        ///     * Create our &quot;modernizr&quot; element that we do most feature tests on.
        ///     */
        ///    mod = &apos;modernizr&apos;,
        ///    modElem = document.createElement(mod),
        ///    mStyle = modE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modernizr {
            get {
                return ResourceManager.GetString("modernizr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ┌────────────────────────────────────────────────────────────────────┐ \\
        ///// │ Raphaël 2.1.2 - JavaScript Vector Library                          │ \\
        ///// ├────────────────────────────────────────────────────────────────────┤ \\
        ///// │ Copyright © 2008-2012 Dmitry Baranovskiy (http://raphaeljs.com)    │ \\
        ///// │ Copyright © 2008-2012 Sencha Labs (http://sencha.com)              │ \\
        ///// ├────────────────────────────────────────────────────────────────────┤ \\
        ///// │ Licensed under the MIT (http://raphaelj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string raphael {
            get {
                return ResourceManager.GetString("raphael", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! Aphysoft.Share | share.aphysoft.com */
        ///(function (window, $) {
        ///    &quot;use strict&quot;;
        ///
        ///    window.debug = function (arg1) {
        ///        console.debug(arg1);
        ///    };
        ///    window.assert = function (arg1, arg2, arg3) {
        ///        console.assert(arg1, arg2, arg3)
        ///    };
        ///
        ///    function escapeRegExp(string) {
        ///        return string.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, &quot;\\$1&quot;);
        ///    }
        ///
        ///    // jquery document object
        ///    $.window = $(window);
        ///
        ///    // shorthand type detection for jQuery
        ///    $.isObject = funct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // three.min.js - http://github.com/mrdoob/three.js
        ///&apos;use strict&apos;;var THREE=THREE||{REVISION:&quot;50&quot;};void 0===self.console&amp;&amp;(self.console={info:function(){},log:function(){},debug:function(){},warn:function(){},error:function(){}});void 0===self.Int32Array&amp;&amp;(self.Int32Array=Array,self.Float32Array=Array);
        ///(function(){for(var a=0,b=[&quot;ms&quot;,&quot;moz&quot;,&quot;webkit&quot;,&quot;o&quot;],c=0;c&lt;b.length&amp;&amp;!window.requestAnimationFrame;++c){window.requestAnimationFrame=window[b[c]+&quot;RequestAnimationFrame&quot;];window.cancelAnimationFrame=window[b[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string three {
            get {
                return ResourceManager.GetString("three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! Aphysoft.Share UI | share.aphysoft.com */
        ///(function ($) {
        ///    // use strict failed... :(
        ///
        ///    
        ///})(jQuery);
        ///.
        /// </summary>
        internal static string ui {
            get {
                return ResourceManager.GetString("ui", resourceCulture);
            }
        }
    }
}
